name: Sync Labels
on:
  push:
    paths: [.github/labels.yml]
  workflow_dispatch:
permissions:
  contents: read
  issues: write
  metadata: read
jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crazy-max/ghaction-github-labeler@v5
        with:
          yaml_file: .github/labels.yml
          skip_delete: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
