name: A-1 Bot — Issue Triage
on:
  issues:
    types: [opened]

# important: must allow writing to issues
permissions:
  issues: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: "Thanks for opening this! The A-1 bot is online ✅"
            });
